trigger:
- none

variables:
  IISWebsiteName: 'AzureTestProject'

resources:
  pipelines:
  - pipeline: 'buildPipeline'
    project: 'AzureTestProject'
    source: 'Build pipeline'
    branch: 'main'    
    trigger:
     branches:
     - main