# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

resources:
  pipelines:
  - pipeline: '854ed55a-4188-466d-9beb-97635eb75f1c'
    project: 'AzureTestProject'
    source: 'Build pipeline'
    branch: 'main'

stages:
  - stage: DeployWebsite
    displayName: ' Deploy website'        
    pool:
      vmImage: ubuntu-latest
    
    jobs:    
    - deployment: CopyFiles
      displayName: 'Copy files'
      strategy:
       runOnce:
         deploy:           
          steps:
          - checkout: none
          
          - download: '854ed55a-4188-466d-9beb-97635eb75f1c'
            artifact: 'RoundTheCode'
            displayName: 'Download Pipeline Artifacts'