trigger:
- none

variables:
  IISWebsiteName: 'AzureTestProject'

resources:
  pipelines:
  - pipeline: 'buildPipeline'
    project: 'AzureTestProject'
    source: 'Build pipeline'
    branch: 'main'
    trigger: true


stages:
  - stage: DeployWebsite
    displayName: 'Deploy website'        
    pool:
      vmImage: windows-latest
    
    jobs:    
    - deployment: DeployWebsite
      displayName: 'Deploy website'
      environment: 'Production.DAVE'
      strategy:
       runOnce:
         deploy:           
          steps:
          - checkout: none
          
          - download: 'buildPipeline'
            name: 'DownloadBuildArtifacts'            
            displayName: 'Download build artifacts (Build Id: $(resources.pipeline.buildPipeline.runID))'
            artifact: 'AzureTestProject'          