trigger:
- none

variables:
  IISWebsiteName: 'AzureTestProject'

resources:
  pipelines:
  - pipeline: 'abcd'
    project: 'AzureTestProject'
    source: 'Build pipeline'
    branch: 'main'    

stages:
  - stage: DeployWebsite
    displayName: 'Deploy website'        
    pool:
      vmImage: windows-latest
    
    jobs:    
    - deployment: DeployWebsite
      displayName: 'Deploy website'
      environment: 'Windows 11 server.DAVE'
      strategy:
       runOnce:
         deploy:           
          steps:
          - checkout: none
          
          - download: 'abcd'
            name: 'DownloadBuildArtifacts'            
            displayName: 'Download build artifacts'
            artifact: 'AzureTestProject'
                    
          - task: IISWebAppManagementOnMachineGroup@0
            name: 'StopIIS'
            displayName: 'Stop IIS website - ${{ variables.IISWebsiteName }}'
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'StopWebsite'
              StartStopWebsiteName: '${{ variables.IISWebsiteName }}'   
                          
          - task: IISWebAppDeploymentOnMachineGroup@0
            name: 'DeployIIS'
            displayName: 'Deploy IIS website - ${{ variables.IISWebsiteName }}'          
            inputs:
              WebSiteName: '${{ variables.IISWebsiteName }}'              
              Package: '$(Pipeline.Workspace)\abcd\AzureTestProject\RoundTheCode.AzureTestProject'
              TakeAppOfflineFlag: true
          
          - task: IISWebAppManagementOnMachineGroup@0
            name: 'StartIIS'
            displayName: 'Start IIS website - ${{ variables.IISWebsiteName }}'                
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'StartWebsite'
              StartStopWebsiteName: '${{ variables.IISWebsiteName }}'    