# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
  buildPipeline: '854ed55a-4188-466d-9beb-97635eb75f1c'
  IISWebsiteName: 'AzureTestProject'

resources:
  pipelines:
  - pipeline: ${{ variables.buildPipeline }}
    project: 'AzureTestProject'
    source: 'Build pipeline'
    branch: 'main'

stages:
  - stage: DeployWebsite
    displayName: 'Deploy website'        
    pool:
      vmImage: windows-latest
    
    jobs:    
    - deployment: DeployWebsite
      displayName: 'Deploy website'
      environment: 'Production.DAVE'
      strategy:
       runOnce:
         deploy:           
          steps:
          - checkout: none
          
          - download: ${{ variables.buildPipeline }}
            artifact: 'drop'
            displayName: 'Download Pipeline Artifacts'
          
          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'StopWebsite'
              StartStopWebsiteName: ${{ variables.IISWebsiteName }}